### ISSUE TITLE
Scraper doesn't appear to handle pagination

### ISSUE THREAD

**Issue by fitzoh** [CailinPitt/AwareOSU#1]
If there is a day with a particularly high amount of crime, CPD's web portal will paginate the results [example](http://www.columbuspolice.org/reports/Results?from=10/19/2015&to=10/26/2015&loc=all&types=9).
There's a chance of under-reporting crime on heavy days.

**Comment by cailinpitt** [comment]
I'm aware. The reason I don't worry about that is because on a given day in [Zone 4](http://www.columbuspolice.org/reports/Results?from=10/26/2015&to=10/26/2015&loc=zon4&types=9) (which is where I scrape), it usually doesn't fill an entire page. I may have to add support for pages soon, as my assumption may not be correct 100% of the time
